USE [master]
GO

/****** Object:  Database [TrafikuUrban]    Script Date: 6/18/2019 10:51:14 PM ******/
DROP DATABASE [TrafikuUrban]
GO

/****** Object:  Database [TrafikuUrban]    Script Date: 6/18/2019 10:51:14 PM ******/
CREATE DATABASE [TrafikuUrban]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TrafikuUrban', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\TrafikuUrban.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TrafikuUrban_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\TrafikuUrban_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TrafikuUrban] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrafikuUrban].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TrafikuUrban] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TrafikuUrban] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TrafikuUrban] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TrafikuUrban] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TrafikuUrban] SET ARITHABORT OFF 
GO

ALTER DATABASE [TrafikuUrban] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TrafikuUrban] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TrafikuUrban] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TrafikuUrban] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TrafikuUrban] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TrafikuUrban] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TrafikuUrban] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TrafikuUrban] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TrafikuUrban] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TrafikuUrban] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TrafikuUrban] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TrafikuUrban] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TrafikuUrban] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TrafikuUrban] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TrafikuUrban] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TrafikuUrban] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TrafikuUrban] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TrafikuUrban] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TrafikuUrban] SET  MULTI_USER 
GO

ALTER DATABASE [TrafikuUrban] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TrafikuUrban] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TrafikuUrban] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TrafikuUrban] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TrafikuUrban] SET  READ_WRITE 
GO

